#Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV['AWS_KEY']
    aws.secret_access_key = ENV['AWS_SECRET']
    aws.keypair_name = ENV['AWS_KEYNAME']
    aws.ami = "ami-f4cc1de2"
    aws.region = "us-east-1"
    aws.security_groups = ['launch-wizard-2']
    aws.instance_type = "t2.micro"
    override.vm.box = "dummy"
    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = ENV['AWS_KEYPATH']
  config.vm.provision "shell", path: "bootstrap.sh"
  end
end
